@echo off
REM ****************************************************************************
REM Vivado (TM) v2024.1 (64-bit)
REM
REM Filename    : simulate.bat
REM Simulator   : AMD Vivado Simulator
REM Description : Script for simulating the design by launching the simulator
REM
REM Generated by Vivado on Sat Nov 08 21:27:39 -0800 2025
REM SW Build 5076996 on Wed May 22 18:37:14 MDT 2024
REM
REM Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
REM Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
REM
REM usage: simulate.bat
REM
REM ****************************************************************************
REM simulate design
echo "xsim alu_test_behav -key {Behavioral:sim_1:Functional:alu_test} -tclbatch alu_test.tcl -view C:/Users/anayf/ALU_Project/tb_adder_circuit_behav.wcfg -view C:/Users/anayf/ALU_Project/tb_subtractor_circuit_behav.wcfg -view C:/Users/anayf/ALU_Project/tb_mult_circuit_behav.wcfg -view C:/Users/anayf/ALU_Project/tb_two_comp_behav.wcfg -view C:/Users/anayf/ALU_Project/tb_and_circuit_behav.wcfg -view C:/Users/anayf/ALU_Project/tb_or_circuit_behav.wcfg -view C:/Users/anayf/ALU_Project/tb_shift_left_behav.wcfg -view C:/Users/anayf/ALU_Project/tb_shift_right_behav.wcfg -view C:/Users/anayf/ALU_Project/alu_test_behav.wcfg -log simulate.log"
call xsim  alu_test_behav -key {Behavioral:sim_1:Functional:alu_test} -tclbatch alu_test.tcl -view C:/Users/anayf/ALU_Project/tb_adder_circuit_behav.wcfg -view C:/Users/anayf/ALU_Project/tb_subtractor_circuit_behav.wcfg -view C:/Users/anayf/ALU_Project/tb_mult_circuit_behav.wcfg -view C:/Users/anayf/ALU_Project/tb_two_comp_behav.wcfg -view C:/Users/anayf/ALU_Project/tb_and_circuit_behav.wcfg -view C:/Users/anayf/ALU_Project/tb_or_circuit_behav.wcfg -view C:/Users/anayf/ALU_Project/tb_shift_left_behav.wcfg -view C:/Users/anayf/ALU_Project/tb_shift_right_behav.wcfg -view C:/Users/anayf/ALU_Project/alu_test_behav.wcfg -log simulate.log
if "%errorlevel%"=="0" goto SUCCESS
if "%errorlevel%"=="1" goto END
:END
exit 1
:SUCCESS
exit 0
